### ISSUE TITLE
Having multiple `allowExceptCaseInsensitiveParams` together with `disallowedAttributes` does not work

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#238]
I'm trying to prevent the following:
```php
class Entity {
    #[Column(name: 'start_date_parsed', type: 'datetime', nullable: true)]
    private ?DateTimeInterface $parsedStartDate;
}
```

I can do that with the following config:

```php
<?php

declare(strict_types=1);

return [
    'parameters' => [
        'disallowedAttributes' => [
            [
                'attribute' => Doctrine\ORM\Mapping\Column::class,
                'message' => 'use `utc_datetime_immutable` instead.',
                'allowExceptCaseInsensitiveParams' => [
                    [
                        'name' => 'type',
                        'position' => 2,
                        'value' => 'datetime',
                    ],
                ],
            ],
        ],
    ],
];
```

It produces:
```
Attribute Doctrine\ORM\Mapping\Column is forbidden, use `utc_datetime_immutable` instead.
```

But as soon as I add another disallowed attribute, it stops working:
```php
<?php

declare(strict_types=1);

return [
    'parameters' => [
        'disallowedAttributes' => [
            [
                'attribute' => Doctrine\ORM\Mapping\Column::class,
                'message' => 'use `utc_datetime_immutable` instead.',
                'allowExceptCaseInsensitiveParams' => [
                    [
                        'name' => 'type',
                        'position' => 2,
                        'value' => 'datetime',
                    ],
                ],
            ],
            [
                'attribute' => Doctrine\ORM\Mapping\Column::class,
                'message' => 'use `utc_datetime_immutable` instead.',
                'allowExceptCaseInsensitiveParams' => [
                    [
                        'name' => 'type',
                        'position' => 2,
                        'value' => 'datetime_immutable',
                    ],
                ],
            ],
        ],
    ],
];
```

It's interesting, because this does seem to work for normal functions:
https://github.com/spaze/phpstan-disallowed-calls/blob/90fdf80dfd69fc7eebd3535e4a7b1aae273f1d00/disallowed-insecure-calls.neon#L15-L24

**Comment by ruudk** [comment]
For now, this seems to work:
```php
<?php

declare(strict_types=1);

return [
    'parameters' => [
        'disallowedAttributes' => [
            [
                'attribute' => Doctrine\ORM\Mapping\Column::class,
                'message' => 'use `utc_datetime_immutable` instead.',
                'allowExceptParams' => [
                    [
                        'name' => 'type',
                        'position' => 2,
                        'typeString' => '"datetime"|"datetime_immutable"',
                    ],
                ],
            ],
        ],
    ],
];
```

**Comment by spaze** [comment]
Thanks for the bug, nice catch! For some reason the `isAllowed` method is called differently for functions/methods and for attributes:

https://github.com/spaze/phpstan-disallowed-calls/blob/90fdf80dfd69fc7eebd3535e4a7b1aae273f1d00/src/RuleErrors/DisallowedCallsRuleErrors.php#L56-L60

https://github.com/spaze/phpstan-disallowed-calls/blob/90fdf80dfd69fc7eebd3535e4a7b1aae273f1d00/src/RuleErrors/DisallowedAttributeRuleErrors.php#L49-L51

So that's probably why it works for functions, but not for attributes.

For now, I have written a test f22ee424d316db7f49fcca86b086d5159e17b794, a [failing](https://github.com/spaze/phpstan-disallowed-calls/actions/runs/7456104489/job/20286238839#step:6:40) one, will fix once there's a bit more brain power. And more sleep 😆

**Comment by spaze** [comment]
The reason is that attributes and most other "calls" use a simple key when adding items from the config (the name of the thing):
https://github.com/spaze/phpstan-disallowed-calls/blob/90fdf80dfd69fc7eebd3535e4a7b1aae273f1d00/src/DisallowedAttributeFactory.php#L51

while calls use a composite key (the reason being that some functions/methods come pre-configured in `.neon` files and you may want to re-allow them based on the params used):
https://github.com/spaze/phpstan-disallowed-calls/blob/90fdf80dfd69fc7eebd3535e4a7b1aae273f1d00/src/DisallowedCallFactory.php#L65

This is not very clever but I'm not sure how to do it better, there's always a "but". So for now this will stay.

@ruudk You can use the `typeString` config as you found out, or you can merge those two attribute configs into one like
```php
[
	'attribute' => AttributeColumn::class,
	'message' => 'use `utc_datetime_immutable` instead.',
	'allowExceptCaseInsensitiveParams' => [
		[
			'name' => 'type',
			'position' => 2,
			'value' => 'datetime',
		],
		[
			'name' => 'type',
			'position' => 2,
			'value' => 'datetime_immutable',
		],
	],
],
```

Notice there's just one `'attribute' => AttributeColumn::class` item but the `allowExceptCaseInsensitiveParams` array has two records for the `type` param. I'll add a test for this case.
