### ISSUE TITLE
Support language constructs

### ISSUE THREAD

**Issue by AlexandruGG** [spaze/phpstan-disallowed-calls#69]
Hello 👋 

Firstly, thank you for creating this package. I really like the ability to add my own rules for code that shouldn't be used.

I couldn't manage to find anywhere info regarding the support for language constructs like `die`, `exit` etc. Are these supported or not currently? I tried adding them under `disallowedFunctionCalls` because I saw this in the readme, but that doesn't seem to work:
_You can treat eval() as a function (although it's a language construct) and disallow it in disallowedFunctionCalls._

Am I missing something? If the case is they are not currently supported, how involved do you think it would be to support them? I can see [ekino/phpstan-banned-code](https://github.com/ekino/phpstan-banned-code) supports them but the implementation of the whole thing there is completely different and a lot simpler (I'm not sure what the drawbacks are!).

Cheers!

**Comment by spaze** [comment]
Hey, happy you like the package! And thanks for the issue.

Some language constructs are supported (like `eval()`) but most aren't, and I even think `eval()` is the only one currently supported. The reason is that they need to be explicitly listed and I just haven't added them because I haven't needed it yet :-)

However, they should be easy to add, let me see.

**Comment by spaze** [comment]
I have now released [1.5.0](https://github.com/spaze/phpstan-disallowed-calls/releases/tag/v1.5.0) that supports `die`/`exit` and `empty`. Let me know if there are some more that you'd like to see supported.

**Comment by AlexandruGG** [comment]
@spaze thank you for adding support for those so quickly! 🚀 

If I'll want others I can follow that example PR and submit my own :)

**Comment by ruudk** [comment]
Thanks for adding this. Much appreciated ❤️ 

Can we also support `echo` and `print` in the same way? I'd be happy to submit a PR if you would accept it :)

**Comment by spaze** [comment]
> Can we also support `echo` and `print` in the same way? I'd be happy to submit a PR if you would accept it :)

@ruudk Yeah, thought about those now as you've mentioned them. A PR is welcome and I'd (most probably) accept it. These can be easily _confused_ with functions so I guess it makes sense to support them.

I was and still am reluctant adding support for control structures like `else`/`elseif` (#68) but things that "look like functions" should be fine.

If you're going to submit a PR please note that I've done some changes today in the master branch that should make it a tiny bit easier. Also tests fail currently due to a method being called that's not covered by PHPStan's backward compatibility promise. The method [will be covered](https://github.com/phpstan/phpstan/discussions/5306) by the promise in the next release of PHPStan so don't care about the failing test now.

Thanks!
